IDIR =../include
CC=gcc
CFLAGS=-I$(IDIR)

ODIR=obj
LDIR =../lib

LIBS=-lm

_DEPS = fibonacci.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = fibonacci.o main.o 
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

default: main

$(ODIR)/%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

main: $(OBJ)
	gcc -o $@ $^ $(CFLAGS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(IDIR)/*~ 